version: "3.8"

services:
  apache_php:
    container_name: apache_php
    image: robisonmachado/apache-php7.4:latest
    user: "1000:1000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    links:
      - mysql
  
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    volumes:
      - ./mysql_backup:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.0.4-apache
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql



    
